#------------------------------------------------------------------------------
# VERY IMPORTANT
# We cannot simply use the default server address because it is set to
# 127.0.0.1 which is an issue because then Leverage Terraform container is not
# able to reach that address. Thus we set 'apiServerAddress' to an address
# that is reachable from within the Leverage Terraform container.
#------------------------------------------------------------------------------
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "192.168.0.85"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
