---
galaxy_info:
  author: Andrew Rothstein
  description: hashicorp vault role
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Alpine
      versions:
        - all
  galaxy_tags:
    - secrets

dependencies:
  - role: andrewrothstein.unarchive-deps
    version: v1.0.10
