---

  - block:

    - name: PRITUNL | Add yum repo
      yum_repository:
        name: pritunl
        description: pritunl repo
        file: pritunl
        baseurl: https://repo.pritunl.com/stable/yum/centos/7/
        gpgcheck: no
      become: yes
      tags:
        - pritunl

    - name: PRITUNL | Install EPEL
      yum: name=epel-release state=present
      when: ansible_distribution != "Fedora"
      become: yes
      tags:
        - pritunl

    - name: PRITUNL | Install dependencies
      yum: name={{item}} state=present
      with_items:
      - openvpn
      when: ansible_distribution != "Fedora"
      become: yes
      tags:
        - pritunl


    - name: PRITUNL | Install dependencies
      dnf: name={{item}} state=present
      with_items:
      - openvpn
      when: ansible_distribution == "Fedora"
      become: yes
      tags:
        - pritunl


    - name: PRITUNL | Install pritunl
      yum: name={{item}} state=present
      with_items:
      - pritunl
      when: ansible_distribution != "Fedora"
      become: yes
      tags:
        - pritunl


    - name: PRITUNL | Install pritunl
      dnf: name={{item}} state=present
      with_items:
      - pritunl
      when: ansible_distribution == "Fedora"
      become: yes
      tags:
        - pritunl


    - name: PRITUNL | Start pritunl
      service: name=pritunl state=started enabled=yes
      when: docker_test is not defined
      become: yes
      tags:
        - pritunl


    when: ansible_os_family == "RedHat"



  - block:

    - name: PRITUNL | Install key
      apt_key: keyserver=keyserver.ubuntu.com id="CF8E292A"
      become: yes
      tags:
        - pritunl

    - name: PRITUNL | Install pritunl repo
      apt_repository:
        repo: "deb http://repo.pritunl.com/stable/apt {{ansible_distribution_release}} main"
        state: present
        filename: pritunl
        state: present
      become: yes
      tags:
        - pritunl

    - name: PRITUNL | Install dependencies
      apt: name={{item}} state=present update_cache=yes
      with_items:
      - openvpn
      become: yes
      tags:
        - pritunl

    - name: PRITUNL | Install pritunl
      apt: name=pritunl state=present update_cache=yes
      become: yes
      tags:
        - pritunl

    - name: PRITUNL | pritunl
      service: name=pritunl state=started enabled=yes
      when: docker_test is not defined
      become: yes
      tags:
        - pritunl


    when: ansible_os_family == "Debian"
