# meta file for docker-machine
---
galaxy_info:
  role_name: docker-machine
  author: Mischa ter Smitten
  company: Oefenweb.nl B.V.
  description: Set up (the latest or a specific version of) Docker Machine in Debian-like systems.
  license: MIT
  min_ansible_version: 2.5.0.0
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - bionic
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
  galaxy_tags:
    - development
    - packaging
    - system
    - docker
dependencies: []
